---
title: "Evaluating the Impact of Weather on Salmonella Prevalence and Serovar Diversity"
author: "Connor Norris"
format:
  docx:
    toc: false
    number-sections: true
    highlight-style: github
bibliography: ../../assets/dataanalysis-references.bib
csl: ../../assets/american-journal-of-epidemiology.csl
---

```{r, echo=FALSE, message=FALSE}
# load a few R packages
library(here)
library(knitr)
```

**Authors**

-   Connor Norris $^{1}$

**Author affiliations**

1.  College of Public Health, University of Georgia, Athens, GA, USA.

$\land$ Corresponding author: cgn18694\@uga.edu

$\dagger$ Disclaimer: The opinions expressed in this article are the author's own and don't reflect their employer.

{{< pagebreak >}}

# Part 1

This project will focus on using weather data to predict the prevalence of *Salmonella* and of specific *Salmonella* serovars of public health concern in creek water. The data for my project was collected by several collaborators of mine from the Shariat Lab at UGA. The project they were working on was a longitudinal study evaluating the population dynamics of *Salmonella* in four creek systems in Georgia. Creek samples were taken from several sites along each system monthly over a period of two years (2021-2023). From samples that were positive for *Salmonella*, a novel technique developed in the Shariat Lab called CRISPR SeroSeq was used to identify the various *Salmonella* serovars present within the sample. Weather data was taken from the UGA Weather Network stations closest to each of the four creek systems.

I plan to use the available weather variables to me (e.g. minimum and maximum temperature, humidity, rainfall, etc.) to predict overall *Salmonella* prevalence as well as the prevalence of a select number of serovars. As of now, I am interested in serovars Infantis, Typhimurium, and Give. S. Infantis and S. Typhimurium have both been identified as serovars of public health concern. S. Give has less of an observed public health impact, but it has been observed to be well adapted to water, making it an interesting comparison group. To do this I will fit a variety of generalized linear models, though my strategy for modeling will be better informed once I do a deeper exploration of the data.
